import { SweetWord, SweetSentence, Emoji } from "./types";

// Sweet Words Collection
export const sweetWords: string[] = [
  // English Sweet Words
  "Sweetheart",
  "Babu",
  "Babudi",
  "Love",
  "Darling",
  "Honey",
  "Pumpkin",
  "Cupcake",
  "Sugar",
  "Sunshine",
  "Boo",
  "Snugglebug",
  "Lovebug",
  "Muffin",
  "Pookie",
  "Lovie",
  "Bunny",
  "Baby",
  "Cutie",
  "Snookums",
  "Buttercup",
  "Precious",
  "Teddy",
  "Cookie",
  "Angel",
  "Dove",
  "Snugglebear",
  "Bubbles",
  "Peach",
  "Cherry",
  "Cuddlebug",
  "Sweet Pea",
  "Lovey-Dovey",
  "Butterfly",
  "Angel Face",
  "Cuddle Muffin",
  "Sweetie Pie",
  "Snuggles",
  "Pudding",
  "Peanut",
  "Cinnamon",
  "Pumpkin Pie",
  "Marshmallow",
  "Tootsie",
  "Sweets",
  "Dumpling",
  "Love Muffin",
  "Cherub",
  "Gummy Bear",
  "Button",
  "Jellybean",
  "Sweetums",
  "Love Dove",
  "Moonbeam",
  "Starshine",
  "Honeybee",
  "Dewdrop",
  "Bambi",
  "Cup of Joy",
  "Sugarplum",
  "Lambchop",
  "Ducky",
  "Snickers",
  "Coconut",
  "Cherry Blossom",
  "Twinkle",
  "Angel Eyes",
  "Lush Lips",
  "Cutie Pie",
];

// Sweet Sentences Collection
export const sweetSentences: string[] = [
  "Love You ❤️",
  "I am Sorry 😢",
  "I Miss You 🥹💖",
  "You are my Sunshine ☀️💛",
  "My Heart Beats for You 💓",
  "You are my Forever 🌎💑",
  "I Love You So Much 💞",
  "You are My Everything 🥰💘",
  "Thinking of You 🌸",
  "You are the Love of My Life 💍",
  "Forever Yours 💌",
  "You Complete Me 🧩💗",
  "My Heart is Yours 💝",
  "Can't Stop Thinking About You 💭❤️",
  "You Make Me Happy 😊💓",
  "My World is Brighter with You ✨",
  "You are My Fairytale ✨💖",
  "My Love for You is Infinite 💞",
  "You and Me Forever 🔗💘",
  "I Want to Hold You Forever 🤗💖",
  "Your Love is a Blessing 🙏❤️",
  "You are the Best Thing in My Life 🌟",
  "Hugs and Kisses Always 💏",
  "Every Moment with You is Special 🎀",
  "You are My Soulmate 💫",
  "I am Lucky to Have You 🍀💖",
  "Your Smile is My Sunshine ☀️",
  "You Make My Heart Skip a Beat 💓",
  "No One Compares to You 💯",
  "Loving You is My Favorite Thing 💕",
  "You are My Safe Haven 🏡💖",
  "I Adore You Beyond Words 🥰",
  "Every Second with You is Precious ⏳💗",
  "You are My Happily Ever After 🏰💖",
  "Holding You Feels Like Home 🏡💝",
  "I Will Love You Always and Forever 💘",
  "Your Love is My Strength 💪❤️",
  "You are My Forever and Always 💖",
  "My Heart Belongs to You 💓",
  "Your Love is My Greatest Gift 🎁💝",
  "I Love You More Than Words Can Say 💕",
  "You Make My Life Beautiful 🌷💖",
  "You are My Dream Come True 🌙💞",
  "Together, We are Unstoppable 💪💞",
  "You are My Sweetest Addiction 🍭💘",
  "You are My Home, My Heart, My Love 🏠❤️",
  "You are the Best Part of My Day 🌅💖",
];

// Cute Emojis Collection
export const cuteEmojis: string[] = [
  "❤️",
  "💕",
  "💖",
  "💘",
  "💞",
  "🌸",
  "✨",
  "🌟",
  "🥰",
  "😍",
  "😻",
  "🌷",
  "💫",
  "🎀",
  "💐",
  "💛",
  "💝",
  "💓",
  "💗",
  "💕",
  "💙",
  "💚",
  "💜",
  "🩷",
  "💖",
  "🩵",
  "💞",
  "💟",
  "🌹",
  "💌",
  "😽",
  "🥺",
  "🫶",
  "🤍",
  "💏",
  "💑",
  "🌈",
  "🪽",
  "💃",
  "🕊️",
];

// Love Stickers Collection (public image paths)
export const stickers: string[] = [
  "./stickers/image1.png",
  "./stickers/image2.png",
  "./stickers/image3.png",
];

// Background Gradients
export const backgroundGradients = [
  "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)",
  "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)",
  "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)",
  "linear-gradient(135deg, #d4fc79 0%, #96e6a1 100%)",
  "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
  "linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)",
  "linear-gradient(135deg, #8EC5FC 0%, #E0C3FC 100%)",
  "linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%)",
  "linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)",
  "linear-gradient(135deg, #fad0c4 0%, #ffd1ff 100%)",
  "linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)",
  "linear-gradient(135deg, #c471f5 0%, #fa71cd 100%)",
  "linear-gradient(135deg, #fccb90 0%, #d57eeb 100%)",
  "linear-gradient(135deg, #ffdde1 0%, #ee9ca7 100%)",
  "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)",
];
